version: '3.9'

services:
  net.services.api:
    container_name: net.services.api
    image: net.services.api:latest
    build:
      context: ../API
      dockerfile: Dockerfile
    networks:
      - rabbitmq_go_net
      - mongo_network
      - api_network
    environment:
      - AppOptions__RabbitMqUri=amqp://guest:guest@net.services.rabbitmq
      - MongoDbHumiditySettings__ConnectionUri=mongodb://root:root@mongo:27017
      - MongoDbPressureSettings__ConnectionUri=mongodb://root:root@mongo:27017
      - MongoDbTemperatureSettings__ConnectionUri=mongodb://root:root@mongo:27017
      - MongoDbWindSettings__ConnectionUri=mongodb://root:root@mongo:27017
    ports:
      - 5001:5000

  net.services.dashboard:
    container_name: net.services.dashboard
    image: net.services.dashboard:latest
    ports:
      - 5002:5000
    build:
      context: ../Dashboard
      dockerfile: Dockerfile
    networks:
      - api_network
    environment:
      - AppOptions__HumidityApiLink=http://net.services.api:5000/api/Humidity
      - AppOptions__PressureApiLink=http://net.services.api:5000/api/Pressure
      - AppOptions__TemperatureApiLink=http://net.services.api:5000/api/Temperature
      - AppOptions__WindApiLink=http://net.services.api:5000/api/Wind

  net.services.messagegenerator:
    container_name: net.services.messagegenerator
    image: net.services.messagegenerator:latest
    build:
      context: ../MessageGenerator
      dockerfile: Dockerfile
    networks:
      - rabbitmq_go_net
    environment:
      - AppOptions__RabbitMqUri=amqp://guest:guest@net.services.rabbitmq
      - AppOptions__HumidityJobCron=0/10 * * * * ?
      - AppOptions__PressureJobCron=0/12 * * * * ?
      - AppOptions__TemperatureJobCron=0/14 * * * * ?
      - AppOptions__WindJobCron=0/16 * * * * ?
      - HumidityValueSettings__From=50
      - HumidityValueSettings__To=90
      - PressureValueSettings__From=980
      - PressureValueSettings__To=1020
      - TemperatureValueSettings__From=-10
      - TemperatureValueSettings__To=20
      - WindValueSettings__From=0
      - WindValueSettings__To=10
      - WindValueSettings__DegreeFrom=0
      - WindValueSettings__DegreeTo=360

  net.services.rabbitmq:
    container_name: net.services.rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mongo_network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    networks:
      - mongo_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
networks:
  rabbitmq_go_net:
  mongo_network:
  api_network:
