version: '3.9'

services:
  net-services-api:
    image: grajpawel/net-services-api:latest
    networks:
      - rabbitmq_go_net
    environment:
      - AppOptions__RabbitMqUri=amqp://guest:guest@net-services-rabbitmq
      - MongoDbHumiditySettings__ConnectionUri=mongodb://root:student@actina15.maas:27017
      - MongoDbPressureSettings__ConnectionUri=mongodb://root:student@actina15.maas:27017
      - MongoDbTemperatureSettings__ConnectionUri=mongodb://root:student@actina15.maas:27017
      - MongoDbWindSettings__ConnectionUri=mongodb://root:student@actina15.maas:27017
    ports:
      - 118:5000
      
  net-services-dashboard:
    image: grajpawel/net-services-dashboard:latest
    ports:
      - 119:5000

  net-services-messagegenerator:
    image: grajpawel/net-services-messagegenerator:latest
    networks:
      - rabbitmq_go_net
    environment:
      - AppOptions__RabbitMqUri=amqp://guest:guest@net-services-rabbitmq

  net-services-rabbitmq:
    image: rabbitmq:management
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net: